# CodeRabbit AI Code Review Configuration
# Documentation: https://docs.coderabbit.ai/configuration

language: "en"

reviews:
  # Automatic review on PR open
  auto_review:
    enabled: true
    # Review on each push to PR
    auto_incremental_review: true
    # Ignore draft PRs
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DRAFT"

  # Review profile: chill | assertive | strict
  profile: "assertive"

  # Path-specific instructions
  path_instructions:
    - path: "scripts/**/*.sh"
      instructions: |
        Review shell scripts for:
        - POSIX compatibility issues
        - Security vulnerabilities (command injection, unquoted variables)
        - Error handling (missing error checks, unchecked exit codes)
        - ShellCheck warnings (SC1091, SC2034, SC2086 are intentionally ignored)
        - Proper quoting of variables
        - Use of safe patterns (printf -v instead of eval)
    - path: "templates/**"
      instructions: |
        Review templates for:
        - Placeholder consistency ({{PLACEHOLDER}} format)
        - Valid configuration syntax
    - path: "tests/**/*.sh"
      instructions: |
        Review test scripts for:
        - Test coverage completeness
        - Proper assertions usage
        - Edge case handling

  # Skip files from review
  path_filters:
    - "!**/*.md"
    - "!.github/**"
    - "!LICENSE"

chat:
  # Allow commands in PR comments
  auto_reply: true
