coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 80%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "spec/**/*"
  - "templates/**/*"
  - "pve-install.sh"
  # Orchestrator files - tested indirectly through function calls
  - "scripts/000-init.sh"
  - "scripts/900-main.sh"
  # System checks with complex mocking requirements (apt, ping, modprobe, etc.)
  - "scripts/041-system-check.sh"
  # Files with tests skipped under kcov due to background processes
  - "scripts/037-parallel-helpers.sh"
  - "scripts/380-configure-finalize.sh"
  - "scripts/003-banner.sh"
