# shellcheck shell=bash
# Network interfaces configuration generator
# Generates /etc/network/interfaces based on BRIDGE_MODE and IPv6 settings

# Generates complete /etc/network/interfaces content
# Uses: BRIDGE_MODE, INTERFACE_NAME, MAIN_IPV4, MAIN_IPV4_GW, MAIN_IPV6, etc.
_generate_interfaces_conf() {
  local mode="${BRIDGE_MODE:-internal}"

  cat <<'EOF'
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

source /etc/network/interfaces.d/*

EOF

  _generate_loopback
  echo ""

  case "$mode" in
    internal)
      # Host IP on physical interface, vmbr0 for NAT
      _generate_iface_static
      echo ""
      _generate_vmbr0_nat
      ;;
    external)
      # Physical interface manual, host IP on vmbr0 bridge
      _generate_iface_manual
      echo ""
      _generate_vmbr0_external
      ;;
    both)
      # Physical interface manual, vmbr0 for external, vmbr1 for NAT
      _generate_iface_manual
      echo ""
      _generate_vmbr0_external
      echo ""
      _generate_vmbr1_nat
      ;;
    *)
      # Fallback to static config if invalid mode - ensures network connectivity
      log "WARNING: Unknown BRIDGE_MODE '${mode}', falling back to static config"
      _generate_iface_static
      echo ""
      _generate_vmbr0_nat
      ;;
  esac
}

# Generate interfaces config to file. $1=output_path
generate_interfaces_file() {
  local output="${1:-./templates/interfaces}"
  _generate_interfaces_conf >"$output"
  log "Generated interfaces config (mode: ${BRIDGE_MODE:-internal})"
}
