# shellcheck shell=bash
# nftables Firewall configuration
# Modern replacement for iptables with unified IPv4/IPv6 rules
# Package installed via batch_install_packages() in 037-parallel-helpers.sh

# Generates complete nftables.conf content
_generate_nftables_conf() {
  cat <<EOF
#!/usr/sbin/nft -f
# nftables firewall configuration for Proxmox VE
# Generated by proxmox-installer
# Bridge mode: ${BRIDGE_MODE:-internal}
# Firewall mode: ${FIREWALL_MODE:-standard}

flush ruleset

# Main filter table for IPv4/IPv6
table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        # Allow established and related connections (stateful firewall)
        ct state established,related accept

        # Drop invalid packets
        ct state invalid drop

        # Allow loopback interface (required for local services)
        iifname "lo" accept

$(_generate_bridge_input_rules)

$(_generate_tailscale_rules)

        # ICMPv4: allow essential types with rate limiting
        ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded } limit rate 10/second accept

        # ICMPv6: allow essential types (required for IPv6 to work properly)
        ip6 nexthdr icmpv6 icmpv6 type { echo-request, echo-reply, destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } limit rate 10/second accept

$(_generate_port_rules "$FIREWALL_MODE")

        # Everything else is dropped (default policy)
    }

    chain forward {
        type filter hook forward priority filter; policy accept;

$(_generate_bridge_forward_rules)

        # Allow established/related
        ct state established,related accept

        # Drop invalid packets
        ct state invalid drop
    }

    chain output {
        type filter hook output priority filter; policy accept;
        # Allow all outbound traffic
    }
}

# NAT table for VM internet access (masquerading)
table inet nat {
    chain postrouting {
        type nat hook postrouting priority srcnat;

$(_generate_nat_rules)
    }
}
EOF
}

# Main implementation for nftables configuration
_config_nftables() {
  # Set up iptables-nft compatibility layer
  remote_exec '
    update-alternatives --set iptables /usr/sbin/iptables-nft
    update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
  ' || log "WARNING: Could not set iptables-nft alternatives"

  # Generate complete config
  local config_file="./templates/nftables.conf.generated"
  _generate_nftables_conf >"$config_file"

  log "Generated nftables config (mode: $FIREWALL_MODE, bridge: $BRIDGE_MODE)"

  # Deploy to VM
  remote_copy "$config_file" "/etc/nftables.conf" || {
    log "ERROR: Failed to deploy nftables config"
    rm -f "$config_file"
    return 1
  }

  # Validate syntax
  remote_exec "nft -c -f /etc/nftables.conf" || {
    log "ERROR: nftables config syntax validation failed"
    rm -f "$config_file"
    return 1
  }

  # Enable service
  remote_exec "systemctl enable --now nftables" || {
    log "ERROR: Failed to enable nftables"
    rm -f "$config_file"
    return 1
  }

  rm -f "$config_file"
}

# Public function: configures nftables firewall
# Modes: stealth (VPN only), strict (SSH only), standard (SSH + Web UI)
configure_firewall() {
  if [[ $INSTALL_FIREWALL != "yes" ]]; then
    log "Skipping firewall configuration (INSTALL_FIREWALL=$INSTALL_FIREWALL)"
    return 0
  fi

  log "Configuring nftables firewall (mode: $FIREWALL_MODE, bridge: $BRIDGE_MODE)"

  local mode_display=""
  case "$FIREWALL_MODE" in
    stealth) mode_display="stealth (Tailscale only)" ;;
    strict) mode_display="strict (SSH only)" ;;
    standard) mode_display="standard (SSH + Web UI)" ;;
    *) mode_display="$FIREWALL_MODE" ;;
  esac

  if ! run_with_progress "Configuring nftables firewall" "Firewall configured ($mode_display)" _config_nftables; then
    log "WARNING: Firewall setup failed"
  fi
  return 0
}
